name: Trigger auto deployment for app-langchain-example

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/app-langchain-example-AutoDeployTrigger-57a96586-89a5-44de-81f5-bfd35333c3dd.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APPLANGCHAINEXAMPLE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APPLANGCHAINEXAMPLE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APPLANGCHAINEXAMPLE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.APPLANGCHAINEXAMPLE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APPLANGCHAINEXAMPLE_REGISTRY_PASSWORD }}
          containerAppName: app-langchain-example
          resourceGroup: rg-generative-ai
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


